name = "SoleTraits"
uuid = "f0cd7361-857b-4e5b-8aae-3a26fab9cfa9"
authors = ["Eduard I. STAN", "Giovanni PAGLIARINI"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
